//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCarrito
    {
        public int Consecutivo { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int ConsecutivoProducto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tProductos tProductos { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
