//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalles
    {
        public int IdDetalle { get; set; }
        public int ConsecutivoPed { get; set; }
        public int ConsecutivoProd { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual tPedidos tPedidos { get; set; }
        public virtual tProductos tProductos { get; set; }
    }
}
