//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalles
    {
        public int IdDetalle { get; set; }
        public int ConsecutivoPed { get; set; }
        public int ConsecutivoProd { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual tPedidos tPedidos { get; set; }
        public virtual tProductos tProductos { get; set; }
    }
}
