//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPagos
    {
        public int IdPago { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int ConsecutivoPed { get; set; }
        public int ConsecutivoMet { get; set; }
    
        public virtual tMetodos tMetodos { get; set; }
        public virtual tPedidos tPedidos { get; set; }
    }
}
